### ISSUE TITLE
Step fails to install sudo

### ISSUE THREAD

**Issue by apinnecke** [ReleaseQueue/wercker-step-terraform#1]
Hey folks,

thanks for providing this step! 💪  Unfortunately I'm unable getting my wercker.yml to work with this step running since the script tries to install `sudo`. This is the output I'm receiving:

```
source "/pipeline/run-terraform-69fd16f6-82bb-4a8d-a4c7-7b2d3e1b2834/run.sh" < /dev/null
/pipeline/run-terraform-69fd16f6-82bb-4a8d-a4c7-7b2d3e1b2834/run_terraform: line 1673: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8): No such file or directory
/pipeline/run-terraform-69fd16f6-82bb-4a8d-a4c7-7b2d3e1b2834/run_terraform: line 1674: warning: setlocale: LC_CTYPE: cannot change locale (en_US.UTF-8): No such file or directory
/pipeline/run-terraform-69fd16f6-82bb-4a8d-a4c7-7b2d3e1b2834/run_terraform: line 1675: warning: setlocale: LC_MESSAGES: cannot change locale (en_US.UTF-8): No such file or directory
/pipeline/run-terraform-69fd16f6-82bb-4a8d-a4c7-7b2d3e1b2834/run_terraform: line 1677: warning: setlocale: LC_NUMERIC: cannot change locale (en_US.UTF-8): No such file or directory
/pipeline/run-terraform-69fd16f6-82bb-4a8d-a4c7-7b2d3e1b2834/run_terraform: line 1678: warning: setlocale: LC_TIME: cannot change locale (en_US.UTF-8): No such file or directory
run_terraform_src: WARN: Installing missing packages 'sudo gawk curl p7zip-full'
run_terraform_src: FAIL: Essential dependency 'sudo' not found on the PATH (with arguments '-p
```

This is my `wercker.yml` with some anonymized data:

```
build:
    box: ubuntu
    steps:
    - releasequeue/run-terraform@0.0.15:
        action: "plan"
        out_file: "output_file"
        state_stor_bucket: "fancy-bucket-123"
        state_stor_bucket_region: "eu-central-1"
        state_stor_key: "terraform.tfstate"
    - releasequeue/run-terraform@0.0.15:
        action: "apply"
        in_file: "output_file"
        state_stor_bucket: "fancy-bucket-123"
        state_stor_bucket_region: "eu-central-1"
        state_stor_key: "terraform.tfstate"
    after-steps:
    - slack-notifier:
        url: $SLACK_URL
        channel: builds
        username: Wercker - Terraform
```

Do I need to use a special box for this step? Thanks in advance for any help! :)

**Comment by ringods** [comment]
Hello @apinnecke, this step hasn't gotten the appropriate attention lately. I should test it myself again, and update for TF 0.7 (and the upcoming 0.8).

**Comment by apinnecke** [comment]
Hey @ringods,

thanks a lot for the super quick response! So do you find some time to do this within the next week? Since this isn't urgent at all I'd just need to know weather some near-future work is planned to shift to a different solution otherwise. :)

**Comment by ringods** [comment]
I'm also watching this issue to be resolved: https://github.com/hashicorp/terraform/issues/7927

With that in place, one could `terraform plan` in Wercker build phase and `terraform apply` with the plan file in the Wercker deploy phase.

**Comment by ringods** [comment]
And as a current workaround, you can also this box inside a custom pipeline:

```
box:
  id: hashicorp/terraform:0.7.12
  # Set a shell as entrypoint for wercker. The image defaults to running terraform immediately.
  entrypoint: /bin/bash -c
```
